# Generated by Django 3.0.2 on 2020-03-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
