# Generated by Django 3.0.2 on 2020-03-05 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prodName',
            field=models.CharField(default='pene asado', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='date_price',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 23, 8, 25, 197011)),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 23, 8, 25, 197011)),
        ),
    ]
