# Generated by Django 3.0.2 on 2020-03-06 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date_price',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 8, 24, 15, 925269)),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 8, 24, 15, 925269)),
        ),
    ]
