# Generated by Django 3.0.2 on 2020-03-04 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200303_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Corts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Animals'),
        ),
        migrations.AlterField(
            model_name='products',
            name='corte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Corts'),
        ),
        migrations.DeleteModel(
            name='Animales',
        ),
        migrations.DeleteModel(
            name='Cortes',
        ),
    ]
