# Generated by Django 3.0.2 on 2020-03-06 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200306_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date_price',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 8, 44, 18, 48972)),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 8, 44, 18, 48972)),
        ),
    ]
