# Generated by Django 3.0.2 on 2020-03-06 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200305_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date_price',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 2, 13, 32, 460260)),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 2, 13, 32, 460260)),
        ),
    ]
