# Generated by Django 3.0.2 on 2020-03-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200303_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='products',
            name='corte',
        ),
    ]
