# Generated by Django 3.0.2 on 2020-03-04 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200303_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='animal',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='products.Animals'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='corte',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='products.Corts'),
            preserve_default=False,
        ),
    ]
