# Generated by Django 3.0.2 on 2020-03-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('iva', models.PositiveSmallIntegerField(null=True)),
                ('instrumento_pago', models.CharField(max_length=15, null=True)),
                ('totalBruto', models.PositiveIntegerField(null=True)),
                ('totalNeto', models.PositiveIntegerField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Cantidad', models.IntegerField()),
                ('Animal', models.CharField(max_length=100)),
                ('Pieza', models.CharField(max_length=100)),
                ('Precio', models.CharField(max_length=100)),
                ('Fecha', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=100, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('descuento', models.PositiveSmallIntegerField(null=True)),
                ('dificultad', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleAcierto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puzzle', models.CharField(max_length=100)),
                ('Aciertos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuzzlesPorOrdenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertado', models.BooleanField(blank=True, null=True)),
                ('descuesto_total', models.PositiveSmallIntegerField(null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsUTILS.Orden')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsUTILS.Puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_orden', models.PositiveSmallIntegerField(null=True)),
                ('Price_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Price')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado', models.BooleanField(null=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Addresses')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelsUTILS.Orden')),
            ],
        ),
    ]
