# Generated by Django 3.0.2 on 2020-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Cantidad', models.IntegerField()),
                ('Animal', models.CharField(max_length=100)),
                ('Pieza', models.CharField(max_length=100)),
                ('Precio', models.CharField(max_length=100)),
                ('Fecha', models.DateField(max_length=100)),
            ],
            options={
                'db_table': 'precio_actual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuzzleAcierto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puzzle', models.CharField(max_length=100)),
                ('Aciertos', models.IntegerField()),
            ],
            options={
                'db_table': 'puzzle_aciertos',
                'managed': False,
            },
        ),
    ]
