# Generated by Django 3.0.2 on 2020-03-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nro_purchases',
        ),
        migrations.AddField(
            model_name='profile',
            name='cedula',
            field=models.PositiveIntegerField(max_length=7, null=True),
        ),
    ]
